name: 'Build Documentation'
description: 'Build the Vite documentation site with all required assets'

runs:
  using: 'composite'
  steps:
    - name: Build documentation site
      shell: bash
      run: |
        # Change to docs directory and install dependencies
        cd docs
        npm install

        # Use copy-docs script from @fjell/docs-template to copy all configured files
        npm run copy-docs

        # Build the Vite documentation site
        npm run build
